IF NOT DEFINED GACUTILEXE32 IF EXIST "%WINSDKNETFXTOOLS%gacutil.exe"     set GACUTILEXE32=%WINSDKNETFXTOOLS%gacutil.exe
set GACUTIL=%ADMIN_PIPE% "%GACUTILEXE32%"

goto :Label%1

:LabelYYY
:LabelYYN
:LabelNFYY
:LabelNFYN
:LabelNYY
:LabelNYN
%GACUTIL% /uf MyTPDesignTime
goto :EOF
