// Table 4.1 "Operator Names"
// Spec 1.9.4-v12

#light
    
let operators = [ (* Operator name *) (* Mangled name *)
                    "[]",       "op_Nil"
                    "::",       "op_Cons"
                    "+",        "op_Addition"
                    "-",        "op_Subtraction"
                    "*",        "op_Multiply"
                    "/",        "op_Division"
                    "@",        "op_Append"
                    "^",        "op_Concatenate"
                    "%",        "op_Modulus"
                    "&&&",      "op_BitwiseAnd"
                    "|||",      "op_BitwiseOr"
                    "^^^",      "op_ExclusiveOr"
                    "<<<",      "op_LeftShift"
                    "~~~",      "op_LogicalNot"
                    ">>>",      "op_RightShift"
                    "~+",       "op_UnaryPlus"
                    "~~",       "op_UnaryNegation"
                    "<=",       "op_LessThanOrEqual"
                    ">=",       "op_GreaterThanOrEqual"
                    "<",        "op_LessThan"
                    ">",        "op_GreaterThan"
                    "|>",       "op_PipeRight"
                    "<|",       "op_PipeLeft"
                    "!",        "op_Dereference"
                    ">>",       "op_ComposeRight"
                    "<<",       "op_ComposeLeft"
                    "<@ @>",    "op_Quotation"
                    "<@@ @@>",  "op_QuotationUntyped"
                    "+=",       "op_AdditionAssignment"
                    "-=",       "op_SubtractionAssignment"
                    "*=",       "op_MultiplyAssignment"
                    "/=",       "op_DivisionAssignment"
                    "..",       "op_Range"
                    ".. ..",    "op_RangeStep"
                    ]
                    
