value constantUnit at line 6 has total size 0
value constantInteger at line 7 has total size 0
value constantValue at line 8 has total size 1
value fieldLookup1 at line 9 has total size 2
value libraryCall1 at line 10 has total size 2
value libraryCall2 at line 11 has total size 1
value constantData1 at line 12 has total size 2
value constantData2 at line 13 has total size 2
value constantTuple1 at line 14 has total size 1
value constantTuple2 at line 15 has total size 1
value indirectCall1 at line 17 has total size 1
value indirectCall2 at line 18 has total size 2
value indirectCall3 at line 19 has total size 3
value sequenceOfIndirectCalls1 at line 20 has total size 4
value ifThenElse at line 21 has total size 5
value patternMatch1 at line 22 has total size 8
value forLoop1 at line 23 has total size 6
value whileLoop1 at line 24 has total size 6
