jobs:

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 90
  strategy:
    maxParallel: 3
    matrix:
      coreclr_release:
        _configuration: Release
        _testKind: testcoreclr
  steps:
  - script: ./eng/cibuild.sh --configuration $(_configuration) --$(_testKind)
  - task: PublishBuildArtifacts@1
    displayName: Publish Build Logs
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(_configuration)'
      ArtifactName: 'Linux $(_configuration) $(_testKind) build log'
      publishLocation: Container
    continueOnError: true
    condition: not(succeeded())
  - task: PublishBuildArtifacts@1
    displayName: Publish Test Results
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/artifacts/TestResults'
      ArtifactName: 'Linux $(_configuration) $(_testKind)'
      publishLocation: Container
    continueOnError: true
    condition: not(succeeded())

- job: Linux_FCS
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 90
  steps:
  - script: ./fcs/build.sh Build
  - task: PublishBuildArtifacts@1
    displayName: Publish Test Results
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/artifacts/TestResults'
      ArtifactName: 'Linux FCS test results'
      publishLocation: Container
    continueOnError: true
    condition: not(succeeded())

- job: MacOS
  pool:
    vmImage: macOS-10.13
  timeoutInMinutes: 90
  strategy:
    maxParallel: 3
    matrix:
      coreclr_release:
        _configuration: Release
        _testKind: testcoreclr
  steps:
  - script: ./eng/cibuild.sh --configuration $(_configuration) --$(_testKind)
  - task: PublishBuildArtifacts@1
    displayName: Publish Build Logs
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(_configuration)'
      ArtifactName: 'MacOS $(_configuration) $(_testKind) build log'
      publishLocation: Container
    continueOnError: true
    condition: not(succeeded())
  - task: PublishBuildArtifacts@1
    displayName: Publish Test Results
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/artifacts/TestResults'
      ArtifactName: 'MacOS $(_configuration) $(_testKind)'
      publishLocation: Container
    continueOnError: true
    condition: not(succeeded())

- job: MacOS_FCS
  pool:
    vmImage: macOS-10.13
  timeoutInMinutes: 90
  steps:
  - script: ./fcs/build.sh Build
  - task: PublishBuildArtifacts@1
    displayName: Publish Test Results
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/artifacts/TestResults'
      ArtifactName: 'MacOS FCS test results'
      publishLocation: Container
    continueOnError: true
    condition: not(succeeded())

- job: Windows
  pool:
    vmImage: vs2017-win2016
  timeoutInMinutes: 120
  strategy:
    maxParallel: 4
    matrix:
      desktop_release:
        _configuration: Release
        _testKind: testDesktop
      coreclr_release:
        _configuration: Release
        _testKind: testCoreclr
      fsharpqa_release:
        _configuration: Release
        _testKind: testFSharpQA
      vs_release:
        _configuration: Release
        _testKind: testVs
  steps:
  - script: eng\CIBuild.cmd -configuration $(_configuration) -$(_testKind)
  - task: PublishBuildArtifacts@1
    displayName: Publish Build Logs
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)\artifacts\log\$(_configuration)'
      ArtifactName: 'Windows $(_configuration) $(_testKind) build log'
      publishLocation: Container
    continueOnError: true
    condition: not(succeeded())
  - task: PublishBuildArtifacts@1
    displayName: Publish Test Results
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)\artifacts\TestResults'
      ArtifactName: 'Windows $(_configuration) $(_testKind) test results'
      publishLocation: Container
    continueOnError: true
    condition: not(succeeded())

- job: Windows_FCS
  pool:
    vmImage: vs2017-win2016
  timeoutInMinutes: 120
  steps:
  - script: fcs\build.cmd TestAndNuget
  - task: PublishBuildArtifacts@1
    displayName: Publish Test Results
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)\artifacts\TestResults'
      ArtifactName: 'Windows FCS test results'
      publishLocation: Container
    continueOnError: true
    condition: not(succeeded())
