# DEPRECATED: F# Compiler Regression Testing Pipeline
# This pipeline has been integrated into azure-pipelines-PR.yml
# The regression test logic is now available as a template at eng/templates/regression-test-jobs.yml
# and is automatically run as part of PR builds.
#
# This file is kept for documentation purposes and can be used as a standalone 
# regression test pipeline if needed in the future.

trigger:
  branches:
    include:
    - main
    - release/*
    - feature/*
  paths:
    include:
    - src/*
    exclude:
    - docs/*
    - .github/*
    - '*.md'

pr:
  branches:
    include:
    - main
    - release/*
    - feature/*
  paths:
    include:
    - src/*
    exclude:
    - docs/*
    - .github/*
    - '*.md'

variables:
  - name: _TeamName
    value: FSharp
  - name: _BuildConfig
    value: Release
  - name: _PublishUsingPipelines
    value: true
  - name: Codeql.Enabled
    value: false  # Disabled for regression tests
  # Pick up pool provider name behavior from shared yaml template
  - template: /eng/common/templates/variables/pool-providers.yml

stages:
- stage: RegressionTest
  displayName: F# Compiler Regression Tests (Standalone)
  jobs:
  # Build the compiler to generate artifacts needed for regression testing
  - job: BuildCompiler
    displayName: Build F# Compiler for Regression Tests
    pool:
      name: $(DncEngPublicBuildPool)
      demands: ImageOverride -equals $(WindowsMachineQueueName)
    timeoutInMinutes: 60
    steps:
    - checkout: self
      clean: true
      displayName: Checkout F# compiler source

    - task: UseDotNet@2
      displayName: install SDK
      inputs:
        packageType: sdk
        version: '10.x'
        includePreviewVersions: true
        workingDirectory: $(Build.SourcesDirectory)
        installationPath: $(Build.SourcesDirectory)/.dotnet

    - script: .\eng\common\dotnet.cmd
      displayName: Ensure correct .NET SDK version

    - script: .\Build.cmd -c $(_BuildConfig) -pack
      env:
        NativeToolsOnMachine: true
      displayName: Build F# compiler and create packages

    - task: PublishPipelineArtifact@1
      displayName: Publish F# Compiler Artifacts
      inputs:
        targetPath: '$(Build.SourcesDirectory)/artifacts'
        artifactName: 'FSharpCompilerArtifacts'
        publishLocation: pipeline
      condition: succeeded()

    - task: PublishPipelineArtifact@1
      displayName: Publish UseLocalCompiler props file
      inputs:
        targetPath: '$(Build.SourcesDirectory)/UseLocalCompiler.Directory.Build.props'
        artifactName: 'UseLocalCompilerProps'
        publishLocation: pipeline
      condition: succeeded()

  # Use the regression test template
  - template: /eng/templates/regression-test-jobs.yml
    parameters:
      testMatrix:
      - repo: fsprojects/FSharpPlus
        commit: f614035b75922aba41ed6a36c2fc986a2171d2b8
        buildScript: build.cmd
        displayName: FSharpPlus