@if "%_echo%"=="" echo off

setlocal

call %~d0%~p0..\..\..\config.bat

if EXIST provided.dll del provided.dll
if ERRORLEVEL 1 goto :Error

if EXIST provided1.dll del provided1.dll
if ERRORLEVEL 1 goto :Error

"%FSC%" --out:provided1.dll -g -a ..\helloWorld\provided.fs
if errorlevel 1 goto :Error

if EXIST provided2.dll del provided2.dll
if ERRORLEVEL 1 goto :Error

"%FSC%" --out:provided2.dll -g -a ..\helloWorld\provided.fs
if errorlevel 1 goto :Error

if EXIST provided3.dll del provided3.dll
if ERRORLEVEL 1 goto :Error

"%FSC%" --out:provided3.dll -g -a ..\helloWorld\provided.fs
if errorlevel 1 goto :Error

if EXIST provided4.dll del provided4.dll
if ERRORLEVEL 1 goto :Error

"%FSC%" --out:provided4.dll -g -a ..\helloWorld\provided.fs
if errorlevel 1 goto :Error

if EXIST providedJ.dll del providedJ.dll
if ERRORLEVEL 1 goto :Error

"%FSC%" --out:providedJ.dll -g -a ..\helloWorld\providedJ.fs
if errorlevel 1 goto :Error

if EXIST providedK.dll del providedK.dll
if ERRORLEVEL 1 goto :Error

"%FSC%" --out:providedK.dll -g -a ..\helloWorld\providedK.fs
if errorlevel 1 goto :Error

"%FSC%" --out:providedNullAssemblyName.dll -g -a ..\helloWorld\providedNullAssemblyName.fsx
if errorlevel 1 goto :Error

call %~d0%~p0\..\build-typeprovider-test.bat

if EXIST provider_with_binary_compat_changes.dll del provider_with_binary_compat_changes.dll
if ERRORLEVEL 1 goto :Error

mkdir bincompat1
pushd bincompat1

xcopy /y ..\*.dll .
if errorlevel 1 goto :Error


"%FSC%" -g -a -o:test_lib.dll -r:provider.dll ..\test.fsx
if ERRORLEVEL 1 goto :Error

"%FSC%" -r:test_lib.dll -r:provider.dll ..\testlib_client.fsx
if ERRORLEVEL 1 goto :Error

popd
mkdir bincompat2
pushd bincompat2

xcopy /y ..\bincompat1\*.dll .


REM overwrite provider.dll
"%FSC%" --define:ADD_AN_OPTIONAL_STATIC_PARAMETER --define:USE_IMPLICIT_ITypeProvider2 --out:provider.dll -g -a ..\provider.fsx
if ERRORLEVEL 1 goto :Error


"%FSC%" -g -a -o:test_lib_recompiled.dll -r:provider.dll ..\test.fsx
if ERRORLEVEL 1 goto :Error

REM This is the important part of the binary compatibility part of the test: the new provider is being used, but 
REM with a binary that was generated w.r.t. the old provider. The new provider can still resolve the references
REM generated by the old provider which are stored in the F# metadata for test_lib.dll
"%FSC%" --define:ADD_AN_OPTIONAL_STATIC_PARAMETER -r:test_lib.dll -r:provider.dll ..\testlib_client.fsx
if ERRORLEVEL 1 goto :Error

"%PEVERIFY%" provider.dll
if ERRORLEVEL 1 goto :Error

"%PEVERIFY%" test_lib.dll
if ERRORLEVEL 1 goto :Error

"%PEVERIFY%" test_lib_recompiled.dll
if ERRORLEVEL 1 goto :Error

"%PEVERIFY%" testlib_client.exe
if ERRORLEVEL 1 goto :Error

endlocal

exit /b %ERRORLEVEL%