attributes.on.nonok.types.fsx (2,6)-(2,8) typecheck error The attribute CustomEqualityAttribute is only meant for discriminated unions or record types.
attributes.on.nonok.types.fsx (2,6)-(2,8) typecheck warning The struct, record or union type 'T1' has an explicit implementation of 'Object.Equals'. Consider implementing a matching override for 'Object.GetHashCode()'
attributes.on.nonok.types.fsx (5,6)-(5,8) typecheck error The attributes CustomEqualityAttribute, CustomComparisonAttribute are only meant for discriminated unions or record types.
attributes.on.nonok.types.fsx (5,6)-(5,8) typecheck error A type with attribute 'CustomComparison' must have an explicit implementation of at least one of 'System.IComparable' or 'System.Collections.IStructuralComparable'
attributes.on.nonok.types.fsx (5,6)-(5,8) typecheck warning The struct, record or union type 'T2' has an explicit implementation of 'Object.Equals'. Consider implementing a matching override for 'Object.GetHashCode()'
attributes.on.nonok.types.fsx (8,6)-(8,8) typecheck error The 'CustomEquality' attribute must be used in conjunction with the 'NoComparison' or 'CustomComparison' attributes
attributes.on.nonok.types.fsx (8,6)-(8,8) typecheck warning The struct, record or union type 'S1' has an explicit implementation of 'Object.Equals'. Consider implementing a matching override for 'Object.GetHashCode()'
attributes.on.nonok.types.fsx (12,6)-(12,8) typecheck error A type with attribute 'CustomComparison' must have an explicit implementation of at least one of 'System.IComparable' or 'System.Collections.IStructuralComparable'
attributes.on.nonok.types.fsx (12,6)-(12,8) typecheck warning The struct, record or union type 'S2' has an explicit implementation of 'Object.Equals'. Consider implementing a matching override for 'Object.GetHashCode()'
attributes.on.nonok.types.fsx (16,6)-(16,8) typecheck error The attribute CustomEqualityAttribute is only meant for discriminated unions or record types.
attributes.on.nonok.types.fsx (16,6)-(16,8) typecheck error A type with attribute 'CustomEquality' must have an explicit implementation of at least one of 'Object.Equals(obj)', 'System.IEquatable<_>' or 'System.Collections.IStructuralEquatable'
attributes.on.nonok.types.fsx (18,6)-(18,8) typecheck error The attributes CustomEqualityAttribute, CustomComparisonAttribute are only meant for discriminated unions or record types.
attributes.on.nonok.types.fsx (18,6)-(18,8) typecheck error A type with attribute 'CustomEquality' must have an explicit implementation of at least one of 'Object.Equals(obj)', 'System.IEquatable<_>' or 'System.Collections.IStructuralEquatable'
attributes.on.nonok.types.fsx (20,6)-(20,8) typecheck error The attribute CustomEqualityAttribute is only meant for discriminated unions or record types.
attributes.on.nonok.types.fsx (20,6)-(20,8) typecheck error A type with attribute 'CustomEquality' must have an explicit implementation of at least one of 'Object.Equals(obj)', 'System.IEquatable<_>' or 'System.Collections.IStructuralEquatable'
attributes.on.nonok.types.fsx (22,6)-(22,8) typecheck error The attributes CustomEqualityAttribute, CustomComparisonAttribute are only meant for discriminated unions or record types.
attributes.on.nonok.types.fsx (22,6)-(22,8) typecheck error A type with attribute 'CustomEquality' must have an explicit implementation of at least one of 'Object.Equals(obj)', 'System.IEquatable<_>' or 'System.Collections.IStructuralEquatable'
attributes.on.nonok.types.fsx (24,6)-(24,8) typecheck error The attribute CustomEqualityAttribute is only meant for discriminated unions or record types.
attributes.on.nonok.types.fsx (24,6)-(24,8) typecheck error A type with attribute 'CustomEquality' must have an explicit implementation of at least one of 'Object.Equals(obj)', 'System.IEquatable<_>' or 'System.Collections.IStructuralEquatable'
attributes.on.nonok.types.fsx (26,6)-(26,8) typecheck error The attributes CustomEqualityAttribute, CustomComparisonAttribute are only meant for discriminated unions or record types.
attributes.on.nonok.types.fsx (26,6)-(26,8) typecheck error A type with attribute 'CustomEquality' must have an explicit implementation of at least one of 'Object.Equals(obj)', 'System.IEquatable<_>' or 'System.Collections.IStructuralEquatable'
attributes.on.nonok.types.fsx (28,8)-(28,10) typecheck error This type uses an invalid mix of the attributes 'NoEquality', 'ReferenceEquality', 'StructuralEquality', 'NoComparison' and 'StructuralComparison'
attributes.on.nonok.types.fsx (28,8)-(28,10) typecheck error A type with attribute 'CustomEquality' must have an explicit implementation of at least one of 'Object.Equals(obj)', 'System.IEquatable<_>' or 'System.Collections.IStructuralEquatable'
attributes.on.nonok.types.fsx (31,8)-(31,10) typecheck error This type uses an invalid mix of the attributes 'NoEquality', 'ReferenceEquality', 'StructuralEquality', 'NoComparison' and 'StructuralComparison'
attributes.on.nonok.types.fsx (31,8)-(31,10) typecheck error A type with attribute 'CustomEquality' must have an explicit implementation of at least one of 'Object.Equals(obj)', 'System.IEquatable<_>' or 'System.Collections.IStructuralEquatable'