// #Conformance #TypesAndModules #Unions 
// Make sure we properly detect field naming collisions
//<Expects id="FS3176" span="(7,16-7,21)" status="error">Named field 'Item2' conflicts with autogenerated name for anonymous field\.</Expects>
//<Expects id="FS3176" span="(10,26-10,27)" status="error">Named field 'A' is used more than once\.</Expects>

type MyDU = 
    | Case1 of Item2 : int * string

type MyDU2 = 
    | Case1 of A : int * A : string