rem DIR=..\..\..\Retail\built\bin\
set DIR=..\..\..\Check\built\bin\
copy %DIR%Fsc.exe.config
copy %DIR%Fsc.exe
copy %DIR%Fsc.pdb
copy %DIR%Fsc.xml
copy %DIR%FSharp.Build.dll
copy %DIR%FSharp.Build.pdb
copy %DIR%FSharp.Build.xml
copy %DIR%FSharp.Compiler.CodeDom.dll
copy %DIR%FSharp.Compiler.CodeDom.pdb
copy %DIR%FSharp.Compiler.CodeDom.xml
copy %DIR%FSharp.Compiler.Interactive.Settings.dll
copy %DIR%FSharp.Compiler.Interactive.Settings.pdb
copy %DIR%FSharp.Compiler.Interactive.Settings.xml
copy %DIR%FSharp.Compiler.dll
copy %DIR%FSharp.Compiler.pdb
copy %DIR%FSharp.Compiler.xml
copy %DIR%FSharp.Compiler.Server.Shared.dll
copy %DIR%FSharp.Compiler.Server.Shared.pdb
copy %DIR%FSharp.Compiler.Server.Shared.xml
copy %DIR%FSharp.Core.dll
copy %DIR%FSharp.Core.pdb
copy %DIR%FSharp.Core.xml
copy %DIR%FSharp.PowerPack.Build.Tasks.dll
copy %DIR%FSharp.PowerPack.Build.Tasks.pdb
copy %DIR%FSharp.PowerPack.Build.Tasks.xml
copy %DIR%FSharp.PowerPack.Linq.dll
copy %DIR%FSharp.PowerPack.Linq.pdb
copy %DIR%FSharp.PowerPack.Linq.xml
copy %DIR%FSharp.PowerPack.Metadata.dll
copy %DIR%FSharp.PowerPack.Metadata.pdb
copy %DIR%FSharp.PowerPack.Metadata.xml
copy %DIR%FSharp.PowerPack.dll
copy %DIR%FSharp.PowerPack.pdb
copy %DIR%FSharp.PowerPack.xml
copy %DIR%FSharp.PowerPack.targets
copy %DIR%Fsi.exe
copy %DIR%Fsi.pdb
copy %DIR%Fsi.xml
copy %DIR%FsLex.exe
copy %DIR%FsLex.pdb
copy %DIR%FsLex.xml
copy %DIR%FsYacc.exe
copy %DIR%FsYacc.pdb
copy %DIR%FsYacc.xml
copy %DIR%Microsoft.FSharp.targets