# Template for F# Compiler Regression Tests
# Tests third-party F# projects with the freshly built compiler

parameters:
- name: testMatrix
  type: object
- name: dependsOn
  type: string
  default: 'EndToEndBuildTests'

jobs:
- ${{ each item in parameters.testMatrix }}:
  - job: RegressionTest_${{ replace(replace(item.repo, '/', '_'), '-', '_') }}_${{ replace(item.displayName, '-', '_') }}
    displayName: 'Regression Test: ${{ item.displayName }}'
    dependsOn: ${{ parameters.dependsOn }}
    ${{ if item.useVmImage }}:
      pool:
        vmImage: ${{ item.useVmImage }}
    ${{ else }}:
      pool:
        name: $(DncEngPublicBuildPool)
        demands: ImageOverride -equals $(_WindowsMachineQueueName)
    timeoutInMinutes: 60
    steps:
    - checkout: self
      displayName: Checkout F# compiler repo (for scripts)

    - task: DownloadPipelineArtifact@2
      displayName: Download F# Compiler FSC Artifacts
      inputs:
        artifactName: 'FSharpCompilerFscArtifacts'
        downloadPath: '$(Pipeline.Workspace)/FSharpCompiler/bin/fsc'

    - task: DownloadPipelineArtifact@2
      displayName: Download F# Core Artifacts
      inputs:
        artifactName: 'FSharpCoreArtifacts'
        downloadPath: '$(Pipeline.Workspace)/FSharpCompiler/bin/FSharp.Core'

    - task: DownloadPipelineArtifact@2
      displayName: Download UseLocalCompiler props
      inputs:
        artifactName: 'UseLocalCompilerProps'
        downloadPath: '$(Pipeline.Workspace)/Props'

    - pwsh: |
        Write-Host "Cloning repository: ${{ item.repo }}"
        git clone https://github.com/${{ item.repo }}.git $(Pipeline.Workspace)/TestRepo
        Set-Location $(Pipeline.Workspace)/TestRepo
        
        Write-Host "Checking out commit: ${{ item.commit }}"
        git checkout ${{ item.commit }}
        
        Write-Host "Successfully checked out ${{ item.repo }} at commit ${{ item.commit }}"
        git log -1 --oneline
        
        Write-Host "Repository structure:"
        Get-ChildItem -Name
        
        Write-Host "Verifying build script exists: ${{ item.buildScript }}"
        if (Test-Path "${{ item.buildScript }}") {
          Write-Host "Build script found: ${{ item.buildScript }}"
        } else {
          Write-Host "Build script not found: ${{ item.buildScript }}"
          Write-Host "Available files in root:"
          Get-ChildItem
          exit 1
        }
      displayName: Checkout ${{ item.displayName }} at specific commit

    - task: UseDotNet@2
      displayName: Install .NET SDK for ${{ item.displayName }}
      inputs:
        packageType: sdk
        useGlobalJson: true
        workingDirectory: $(Pipeline.Workspace)/TestRepo
        installationPath: $(Pipeline.Workspace)/TestRepo/.dotnet

    - pwsh: |
        Set-Location $(Pipeline.Workspace)/TestRepo
        
        Write-Host "Running PrepareRepoForRegressionTesting.fsx..."
        dotnet fsi $(Build.SourcesDirectory)/eng/scripts/PrepareRepoForRegressionTesting.fsx "$(Pipeline.Workspace)/Props/UseLocalCompiler.Directory.Build.props"
        
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Failed to prepare repository for regression testing"
          exit 1
        }
      displayName: Setup local compiler configuration for ${{ item.displayName }}

    - pwsh: |
        Set-Location $(Pipeline.Workspace)/TestRepo
        Write-Host "==========================================="
        Write-Host "Environment Information for ${{ item.displayName }}"
        Write-Host "==========================================="
        dotnet --info
        Write-Host ""
        Write-Host "MSBuild version:"
        dotnet msbuild -version
        Write-Host ""
        Write-Host "F# Compiler artifacts available:"
        Get-ChildItem "$(Pipeline.Workspace)/FSharpCompiler/bin/fsc/Release/net10.0" -Name -ErrorAction SilentlyContinue
        Write-Host ""
        Write-Host "F# Core available:"
        if (Test-Path "$(Pipeline.Workspace)/FSharpCompiler/bin/FSharp.Core/Release/netstandard2.0/FSharp.Core.dll") {
          Write-Host "FSharp.Core.dll found"
        } else {
          Write-Host "FSharp.Core.dll not found"
        }
        Write-Host ""
        Write-Host "Directory.Build.props content:"
        Get-Content "Directory.Build.props"
        Write-Host ""
        Write-Host "==========================================="
      displayName: Report build environment for ${{ item.displayName }}

    - pwsh: |
        Set-Location $(Pipeline.Workspace)/TestRepo
        Write-Host "============================================"
        Write-Host "Starting build for ${{ item.displayName }}"
        Write-Host "Repository: ${{ item.repo }}"
        Write-Host "Commit: ${{ item.commit }}"
        Write-Host "Build Script: ${{ item.buildScript }}"
        Write-Host "============================================"
        Write-Host ""
        
        Write-Host "Executing: ${{ item.buildScript }}"
        if ($IsWindows) {
          cmd /c "${{ item.buildScript }}"
        } else {
          chmod +x "${{ item.buildScript }}"
          bash -c "./${{ item.buildScript }}"
        }
        $exitCode = $LASTEXITCODE
        
        Write-Host ""
        Write-Host "============================================"
        Write-Host "Build completed for ${{ item.displayName }}"
        Write-Host "Exit code: $exitCode"
        Write-Host "============================================"
        
        if ($exitCode -ne 0) {
          exit $exitCode
        }
      displayName: Build ${{ item.displayName }} with local F# compiler
      env:
        LocalFSharpCompilerPath: $(Pipeline.Workspace)/FSharpCompiler
        LoadLocalFSharpBuild: 'true'
        LocalFSharpCompilerConfiguration: Release
        MSBUILDBINARYLOGGERENABLED: 'true'
      timeoutInMinutes: 45

    - task: PublishPipelineArtifact@1
      displayName: Publish ${{ item.displayName }} Binary Logs
      inputs:
        targetPath: '$(Pipeline.Workspace)/TestRepo'
        artifactName: '${{ item.displayName }}_BinaryLogs'
        publishLocation: pipeline
      condition: always()
      continueOnError: true

    - pwsh: |
        Set-Location $(Pipeline.Workspace)/TestRepo
        Write-Host ""
        Write-Host "============================================"
        Write-Host "Regression test completed for ${{ item.displayName }}"
        Write-Host "Repository: ${{ item.repo }}"
        Write-Host "Commit: ${{ item.commit }}"
        Write-Host "Build Script: ${{ item.buildScript }}"
        if ($env:AGENT_JOBSTATUS -eq "Succeeded") {
          Write-Host "Status: SUCCESS"
          Write-Host "The ${{ item.displayName }} library builds successfully with the new F# compiler"
        } else {
          Write-Host "Status: FAILED"
          Write-Host "The ${{ item.displayName }} library failed to build with the new F# compiler"
          Write-Host "Check the build logs and artifacts for details"
        }
        Write-Host "============================================"
        
        Write-Host "Binary logs found:"
        Get-ChildItem "*.binlog" -Recurse -ErrorAction SilentlyContinue | ForEach-Object { Write-Host $_.FullName }
      displayName: Report ${{ item.displayName }} test result
      condition: always()
