<Project>
  <PropertyGroup>
    <ImportDirectoryBuildProps>false</ImportDirectoryBuildProps>
    <ImportDirectoryBuildTargets>false</ImportDirectoryBuildTargets>
    <ImportDirectoryPackagesProps>false</ImportDirectoryPackagesProps>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <NuGetAudit>false</NuGetAudit>
    <RestoreSources>https://www.nuget.org/api/v2</RestoreSources>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NuGetLockFilePath>$(MSBuildProjectName).packages.lock.json</NuGetLockFilePath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Compiler.Service" Version="43.10.100" />
    <PackageReference Include="FSharp.Core" Version="10.0.100" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
