[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.LowPlusPriority::TaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!2>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.TaskBuilder, [FSharp.Core]Microsoft.FSharp.Control.FSharpAsync`1<!!1>, !!0)][offset 0x0000000E][found ref '[FSharp.Core]Microsoft.FSharp.Control.FSharpAsync`1<T1>'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T0,T3>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.LowPlusPriority::TaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!2>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.TaskBuilder, [FSharp.Core]Microsoft.FSharp.Control.FSharpAsync`1<!!1>, !!0)][offset 0x00000016][found value 'TTaskLike2'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T3,T2>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.LowPlusPriority::TaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!1>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.TaskBuilder, !!0, [FSharp.Core]Microsoft.FSharp.Control.FSharpAsync`1<!!2>)][offset 0x0000000E][found value 'TTaskLike1'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T0,T3>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.LowPlusPriority::TaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!1>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.TaskBuilder, !!0, [FSharp.Core]Microsoft.FSharp.Control.FSharpAsync`1<!!2>)][offset 0x00000016][found ref '[FSharp.Core]Microsoft.FSharp.Control.FSharpAsync`1<T2>'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T3,T1>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.LowPlusPriority::BackgroundTaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!2>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.BackgroundTaskBuilder, [FSharp.Core]Microsoft.FSharp.Control.FSharpAsync`1<!!1>, !!0)][offset 0x0000000E][found ref '[FSharp.Core]Microsoft.FSharp.Control.FSharpAsync`1<T1>'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T0,T3>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.LowPlusPriority::BackgroundTaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!2>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.BackgroundTaskBuilder, [FSharp.Core]Microsoft.FSharp.Control.FSharpAsync`1<!!1>, !!0)][offset 0x00000016][found value 'TTaskLike2'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T3,T2>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.LowPlusPriority::BackgroundTaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!1>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.BackgroundTaskBuilder, !!0, [FSharp.Core]Microsoft.FSharp.Control.FSharpAsync`1<!!2>)][offset 0x0000000E][found value 'TTaskLike1'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T0,T3>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.LowPlusPriority::BackgroundTaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!1>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.BackgroundTaskBuilder, !!0, [FSharp.Core]Microsoft.FSharp.Control.FSharpAsync`1<!!2>)][offset 0x00000016][found ref '[FSharp.Core]Microsoft.FSharp.Control.FSharpAsync`1<T2>'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T3,T1>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.MediumPriority::TaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!2>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.TaskBuilder, [S.P.CoreLib]System.Threading.Tasks.Task`1<!!1>, !!0)][offset 0x0000000E][found ref '[S.P.CoreLib]System.Threading.Tasks.Task`1<T1>'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T0,T3>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.MediumPriority::TaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!2>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.TaskBuilder, [S.P.CoreLib]System.Threading.Tasks.Task`1<!!1>, !!0)][offset 0x00000016][found value 'TTaskLike2'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T3,T2>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.MediumPriority::TaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!1>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.TaskBuilder, !!0, [S.P.CoreLib]System.Threading.Tasks.Task`1<!!2>)][offset 0x0000000E][found value 'TTaskLike1'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T0,T3>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.MediumPriority::TaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!1>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.TaskBuilder, !!0, [S.P.CoreLib]System.Threading.Tasks.Task`1<!!2>)][offset 0x00000016][found ref '[S.P.CoreLib]System.Threading.Tasks.Task`1<T2>'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T3,T1>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.MediumPriority::BackgroundTaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!2>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.BackgroundTaskBuilder, [S.P.CoreLib]System.Threading.Tasks.Task`1<!!1>, !!0)][offset 0x0000000E][found ref '[S.P.CoreLib]System.Threading.Tasks.Task`1<T1>'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T0,T3>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.MediumPriority::BackgroundTaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!2>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.BackgroundTaskBuilder, [S.P.CoreLib]System.Threading.Tasks.Task`1<!!1>, !!0)][offset 0x00000016][found value 'TTaskLike2'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T3,T2>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.MediumPriority::BackgroundTaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!1>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.BackgroundTaskBuilder, !!0, [S.P.CoreLib]System.Threading.Tasks.Task`1<!!2>)][offset 0x0000000E][found value 'TTaskLike1'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T0,T3>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.MediumPriority::BackgroundTaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,!!1>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!3,bool>, [FSharp.Core]Microsoft.FSharp.Control.BackgroundTaskBuilder, !!0, [S.P.CoreLib]System.Threading.Tasks.Task`1<!!2>)][offset 0x00000016][found ref '[S.P.CoreLib]System.Threading.Tasks.Task`1<T2>'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T3,T1>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.LowPriority::TaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!4>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!1,!!5>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!4,!!2>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!5,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!4,bool>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!5,bool>, [FSharp.Core]Microsoft.FSharp.Control.TaskBuilder, !!0, !!1)][offset 0x0000000E][found value 'TTaskLike2'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T0,T4>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.LowPriority::TaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!4>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!1,!!5>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!4,!!2>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!5,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!4,bool>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!5,bool>, [FSharp.Core]Microsoft.FSharp.Control.TaskBuilder, !!0, !!1)][offset 0x00000016][found value 'TTaskLike1'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T1,T5>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.LowPriority::BackgroundTaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!4>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!1,!!5>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!4,!!2>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!5,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!4,bool>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!5,bool>, [FSharp.Core]Microsoft.FSharp.Control.BackgroundTaskBuilder, !!0, !!1)][offset 0x0000000E][found value 'TTaskLike2'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T0,T4>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Control.TaskBuilderExtensions.LowPriority::BackgroundTaskBuilder.MergeSources$W([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,!!4>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!1,!!5>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!4,!!2>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!5,!!3>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!4,bool>, [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!5,bool>, [FSharp.Core]Microsoft.FSharp.Control.BackgroundTaskBuilder, !!0, !!1)][offset 0x00000016][found value 'TTaskLike1'][expected ref '[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<T1,T5>'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Collections.ArrayModule+Parallel::Choose([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,Microsoft.FSharp.Core.FSharpOption`1<!!1>>, !!0[])][offset 0x000000A0][found Byte] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Collections.ArrayModule+Parallel::Filter([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,bool>, !!0[])][offset 0x00000029][found Byte] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Collections.ArrayModule+Parallel::Partition([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0,bool>, !!0[])][offset 0x00000038][found Byte] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Collections.ArrayModule+Parallel+Pipe #2 input at line 2250@2254-1::Invoke(int32, [System.Threading.Tasks.Parallel]System.Threading.Tasks.ParallelLoopState, int32)][offset 0x00000030][found Boolean] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Collections.ArrayModule+Parallel+Pipe #2 input at line 2580@2584-1::Invoke(int32, [System.Threading.Tasks.Parallel]System.Threading.Tasks.ParallelLoopState, int32)][offset 0x00000022][found Boolean] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Core.StringModule::Map([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<char,char>, string)][offset 0x00000020][found Short] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Core.StringModule::Map([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<char,char>, string)][offset 0x00000031][found Char] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Core.StringModule::MapIndexed([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<int32,Microsoft.FSharp.Core.FSharpFunc`2<char,char>>, string)][offset 0x00000029][found Short] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Core.StringModule::MapIndexed([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<int32,Microsoft.FSharp.Core.FSharpFunc`2<char,char>>, string)][offset 0x00000033][found Char] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Core.StringModule::Filter([FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<char,bool>, string)][offset 0x00000075][found Char] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Core.Operators::castToString(!!0)][offset 0x00000001][found value 'T'][expected ref 'string'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Core.LanguagePrimitives::retype(!!0)][offset 0x00000001][found value 'T'][expected value 'TResult'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Core.LanguagePrimitives+HashCompare::GenericEqualityCharArray(char[], char[])][offset 0x0000001C][found Short] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Core.LanguagePrimitives+HashCompare::GenericEqualityCharArray(char[], char[])][offset 0x00000023][found Short] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Core.BasicInlinedOperations::castclassPrim(object)][offset 0x00000006][found ref 'T'][expected value 'T'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Core.BasicInlinedOperations::notnullPrim(!!0)][offset 0x00000002][found Nullobjref 'NullReference'][expected value 'T'] Unexpected type on the stack.
[IL]: Error [StackUnexpected]: : Microsoft.FSharp.Core.BasicInlinedOperations::iscastPrim(object)][offset 0x00000006][found ref 'T'][expected value 'T'] Unexpected type on the stack.
