parameters:
  componentBranchName: ''
  insertBuildPolicy: 'Request Perf DDRITs'
  insertTargetBranch: ''
  insertTeamEmail: ''
  insertTeamName: ''
  completeInsertion: 'false' # 'true', 'false', 'auto'
  dependsOn: [build]

stages:
- stage: insert
  dependsOn: build
  displayName: Insert into VS
  jobs:
  - job: Insert_VS
    pool:
      vmImage: vs2017-win2016
    variables:
    - group: DotNet-VSTS-Infra-Access
    - name: InsertAccessToken
      value: $(dn-bot-devdiv-build-rw-code-rw-release-rw)
    - name: InsertBuildPolicy
      value: ${{ parameters.insertBuildPolicy }}
    - name: InsertTargetBranch
      value: ${{ parameters.insertTargetBranch }}
    - name: InsertTeamEmail
      value: ${{ parameters.insertTeamEmail }}
    - name: InsertTeamName
      value: ${{ parameters.insertTeamName }}
    - name: InsertPayloadName
      value: '${{ parameters.insertTeamName }} $(Build.SourceBranchName) $(Build.BuildNumber)'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: Download Insertion Artifacts
      inputs:
        buildType: current
        artifactName: VSSetup
    - task: PowerShell@2
      displayName: Get Publish URLs
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/release/scripts/GetPublishUrls.ps1
        arguments: -accessToken $(System.AccessToken) -buildId $(Build.BuildId) -insertionDir $(Build.ArtifactStagingDirectory)\VSSetup
    - task: PowerShell@2
      displayName: Get versions for default.config
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/release/scripts/GetDefaultConfigVersions.ps1
        arguments: -packagesDir $(Build.ArtifactStagingDirectory)\VSSetup\DevDivPackages
    - task: PowerShell@2
      displayName: Get versions for AssemblyVersions.tt
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/release/scripts/GetAssemblyVersions.ps1
        arguments: -assemblyVersionsPath $(Build.ArtifactStagingDirectory)\VSSetup\DevDivPackages\DependentAssemblyVersions.csv
    - task: PowerShell@2
      displayName: Calculate autocompletion state
      inputs:
        targetType: 'inline'
        pwsh: true
        script: |
          # mark the insertion for auto-completion if:
          #   `parameters.completeInsertion` == `true`
          # OR
          #   `parameters.completeInsertion` == `auto` AND `parameters.insertTargetBranch` does not contain 'rel/'
          $completeInsertion = '${{ parameters.completeInsertion }}'
          $autoComplete = ($completeInsertion -Eq 'true') -Or (($completeInsertion -Eq 'auto') -And (-Not ($env:INSERTTARGETBRANCH.Contains('rel/'))))
          $autoCompleteStr = if ($autoComplete) { 'true' } else { 'false' }
          Write-Host "Setting InsertAutoComplete to '$autoCompleteStr'"
          Write-Host "##vso[task.setvariable variable=InsertAutoComplete]$autoCompleteStr"
    - task: ms-vseng.MicroBuildShipTasks.55100717-a81d-45ea-a363-b8fe3ec375ad.MicroBuildInsertVsPayload@3
      displayName: 'Insert VS Payload'
      inputs:
        LinkWorkItemsToPR: false
      condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], '${{ parameters.componentBranchName }}'), eq(variables['Build.SourceBranch'], 'refs/heads/${{ parameters.componentBranchName }}')))
