// Copyright (c) Microsoft Corporation.  All Rights Reserved.  See License.txt in the project root for license information.

/// One project loaded as two target-framework instances: `plain` compiles without the fourth file
/// and without FOO, `foo` compiles everything with FOO defined.
module FSharp.Editor.Tests.MultiTargetFindReferencesTests

open System
open System.IO
open System.Threading
open Xunit
open Microsoft.CodeAnalysis
open Microsoft.CodeAnalysis.ExternalAccess.FSharp.Editor.FindUsages
open Microsoft.VisualStudio.FSharp.Editor
open Microsoft.VisualStudio.FSharp.Editor.CancellableTasks
open FSharp.Compiler.Text
open FSharp.Editor.Tests.Helpers
open FSharp.Test.ProjectGeneration

let private project =
    SyntheticProject.Create(
        { sourceFile "First" [] with
            SignatureFile = AutoGenerated
            ExtraSource = "let sharedFunc funcParam = funcParam * 2\n"
        },
        { sourceFile "Second" [ "First" ] with
            ExtraSource = "let plainUse x = ModuleFirst.sharedFunc x"
        },
        { sourceFile "Third" [ "First" ] with
            ExtraSource = "#if FOO\nlet fooUse x = ModuleFirst.sharedFunc x\n#endif"
        },
        { sourceFile "Fourth" [ "First" ] with
            ExtraSource = "let fooOnlyFileUse x = ModuleFirst.sharedFunc x"
        }
    )

let private solution, plainId, fooId =
    let solution, instances =
        RoslynTestHelpers.CreateMultiTargetSolution(
            project,
            [
                {
                    Defines = []
                    ExcludedFileIds = [ "Fourth" ]
                }
                {
                    Defines = [ "FOO" ]
                    ExcludedFileIds = []
                }
            ]
        )

    match instances with
    | [ plainId; fooId ] -> solution, plainId, fooId
    | _ -> failwith "two instances expected"

let private firstPath = project.GetFilePath "First"

let private declarationPosition =
    (File.ReadAllText firstPath).IndexOf("sharedFunc", StringComparison.Ordinal)

let private instanceOf index = if index = 0 then plainId else fooId

let private documentIn (projectId: ProjectId) path =
    solution.GetDocumentIdsWithFilePath path
    |> Seq.find (fun id -> id.ProjectId = projectId)
    |> solution.GetDocument

[<Theory>]
[<InlineData(0)>]
[<InlineData(1)>]
let ``every file is searched once, files under conditional compilation and instance-only files included`` (instance: int) =
    let context, foundDefinitions, foundReferences =
        RoslynTestHelpers.CreateFindUsagesContext()

    (FSharpFindUsagesService() :> IFSharpFindUsagesService)
        .FindReferencesAsync(documentIn (instanceOf instance) firstPath, declarationPosition, context)
        .Wait()

    Assert.Equal(1, foundDefinitions.Count)
    // The signature, Second, Third under FOO and Fourth compiled only into foo: one hit each, not one per instance.
    Assert.Equal(4, foundReferences.Count)

/// What Rename works from: the symbol's uses grouped by Roslyn document.
let private usesByDocument (document: Document) =
    let sourceText = document.GetTextAsync(CancellationToken.None).Result
    let textLine = sourceText.Lines.GetLineFromPosition declarationPosition

    let fcsLine = Line.fromZ (sourceText.Lines.GetLinePosition declarationPosition).Line

    let lexerSymbol =
        Tokenizer.getSymbolAtPosition (
            document.Id,
            sourceText,
            declarationPosition,
            document.FilePath,
            [],
            SymbolLookupKind.Greedy,
            false,
            false,
            None,
            CancellationToken.None
        )
        |> Option.defaultWith (fun () -> failwith "symbol not found")

    let _, checkFileResults =
        document.GetFSharpParseAndCheckResultsAsync "MultiTargetFindReferences"
        |> CancellableTask.runSynchronouslyWithoutCancellation

    let symbolUse =
        checkFileResults.GetSymbolUseAtLocation(fcsLine, lexerSymbol.Ident.idRange.EndColumn, textLine.ToString(), lexerSymbol.FullIsland)
        |> Option.defaultWith (fun () -> failwith "symbol use not found")

    SymbolHelpers.getSymbolUsesInSolution (symbolUse, checkFileResults, document)
    |> CancellableTask.runSynchronouslyWithoutCancellation

[<Theory>]
[<InlineData(0)>]
[<InlineData(1)>]
let ``rename gets one document per file, owned by an instance that compiles it`` (instance: int) =
    let uses = usesByDocument (documentIn (instanceOf instance) firstPath)

    let instancesOf fileId =
        [
            for id in uses.Keys do
                if solution.GetDocument(id).FilePath = project.GetFilePath fileId then
                    id.ProjectId
        ]

    let files = [ for id in uses.Keys -> solution.GetDocument(id).FilePath ]
    Assert.Equal(files.Length, List.length (List.distinct files))
    Assert.Equal<ProjectId list>([ instanceOf instance ], instancesOf "Second")
    Assert.Equal<ProjectId list>([ fooId ], instancesOf "Third")
    Assert.Equal<ProjectId list>([ fooId ], instancesOf "Fourth")
