//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.FSharp.UIResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.FSharp.UIResources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Lists.
        /// </summary>
        public static string Completion_Lists {
            get {
                return ResourceManager.GetString("Completion_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_ash underline.
        /// </summary>
        public static string Dash_underline {
            get {
                return ResourceManager.GetString("Dash_underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_ot underline.
        /// </summary>
        public static string Dot_underline {
            get {
                return ResourceManager.GetString("Dot_underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation links.
        /// </summary>
        public static string Navigation_links {
            get {
                return ResourceManager.GetString("Navigation_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show completion list after a character is _deleted.
        /// </summary>
        public static string Show_completion_list_after_a_character_is_deleted {
            get {
                return ResourceManager.GetString("Show_completion_list_after_a_character_is_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show completion list after a character is typed.
        /// </summary>
        public static string Show_completion_list_after_a_character_is_typed {
            get {
                return ResourceManager.GetString("Show_completion_list_after_a_character_is_typed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_how navigation links as.
        /// </summary>
        public static string Show_navigation_links_as {
            get {
                return ResourceManager.GetString("Show_navigation_links_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Solid underline.
        /// </summary>
        public static string Solid_underline {
            get {
                return ResourceManager.GetString("Solid_underline", resourceCulture);
            }
        }
    }
}
