<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <PublishTrimmed>true</PublishTrimmed>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>3879</NoWarn>
    <OtherFlags Condition="'$(LinkMode)' == 'Static'">--staticlink:MetadataLibrary</OtherFlags>
    <OtherFlags Condition="'$(LinkMode)' == 'Standalone'">--standalone</OtherFlags>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <DefineConstants Condition="'$(DisableILLinkSubstitutions)' == 'true'">$(DefineConstants);KEEP_METADATA</DefineConstants>
    <DefineConstants Condition="'$(LinkMode)' != ''">$(DefineConstants);STATIC_LINKED</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
    <ProjectReference Include="Library/MetadataLibrary.fsproj" />
    <EmbeddedResource Include="Substitutions.xml" LogicalName="ILLink.Substitutions.xml" Condition="'$(UserSubstitutions)' == 'App'" />
    <EmbeddedResource Include="Program.fs" LogicalName="marker" Condition="'$(UserSubstitutions)' == 'App'" />
  </ItemGroup>
</Project>
