module FSharpDiagServer.ProjectManager

open System.Collections.Concurrent
open System.IO
open FSharp.Compiler.CodeAnalysis

type ProjectManager(checker: FSharpChecker) =
    let cache = ConcurrentDictionary<string, System.DateTime * FSharpProjectOptions>()

    let isSourceFile (s: string) =
        not (s.StartsWith("-"))
        && (s.EndsWith(".fs", System.StringComparison.OrdinalIgnoreCase)
            || s.EndsWith(".fsi", System.StringComparison.OrdinalIgnoreCase))

    let normalize (path: string) = Path.GetFullPath(path)

    member _.ResolveProjectOptions(fsprojPath: string) =
        async {
            let key = normalize fsprojPath
            let fsprojMtime = File.GetLastWriteTimeUtc(key)

            let current =
                match cache.TryGetValue(key) with
                | true, (mtime, opts) when mtime = fsprojMtime -> Some opts
                | true, _ -> cache.TryRemove(key) |> ignore; None
                | false, _ -> None

            match current with
            | Some opts -> return Ok opts
            | None ->
                let! dtbResult = DesignTimeBuild.run fsprojPath DesignTimeBuild.defaultConfig

                match dtbResult with
                | Error msg -> return Error msg
                | Ok dtb ->
                    let projDir = Path.GetDirectoryName(key)

                    let resolve (s: string) =
                        if Path.IsPathRooted(s) then s else Path.GetFullPath(Path.Combine(projDir, s))

                    let resolvedArgs =
                        dtb.CompilerArgs
                        |> Array.map (fun a -> if isSourceFile a then resolve a else a)

                    let sourceFiles = resolvedArgs |> Array.filter isSourceFile

                    // MSBuild auto-generates AssemblyInfo.fs and buildproperties.fs in the
                    // intermediate output. These are added to @(Compile) but NOT to
                    // FscCommandLineArgs. Include them if they exist and aren't already present.
                    let extraGeneratedFiles =
                        if dtb.IntermediateOutputPath.Length > 0 then
                            let projName = Path.GetFileNameWithoutExtension(key)
                            [| Path.Combine(dtb.IntermediateOutputPath, projName + ".AssemblyInfo.fs")
                               Path.Combine(dtb.IntermediateOutputPath, "buildproperties.fs") |]
                            |> Array.filter (fun f ->
                                File.Exists(f) &&
                                let full = Path.GetFullPath(f)
                                not (sourceFiles |> Array.exists (fun s -> Path.GetFullPath(s) = full)))
                        else [||]
                    let sourceFiles = Array.append sourceFiles extraGeneratedFiles

                    // Generated string resource files (FSComp, FSIstrings, UtilsStrings) must come
                    // before source files that reference them. FscCommandLineArgs doesn't preserve
                    // the CompileBefore ordering from MSBuild.
                    let isGeneratedFirst (s: string) =
                        let name = System.IO.Path.GetFileNameWithoutExtension(s)
                        name = "FSComp" || name = "FSIstrings" || name = "UtilsStrings"
                        || name = "buildproperties"
                    let orderedSources =
                        Array.append
                            (sourceFiles |> Array.filter isGeneratedFirst)
                            (sourceFiles |> Array.filter (not << isGeneratedFirst))
                    let flagsOnly = resolvedArgs |> Array.filter (not << isSourceFile)
                    // Add --nowin32manifest: default.win32manifest may not exist on all platforms
                    let flagsOnly = Array.append flagsOnly [| "--nowin32manifest" |]
                    // Embed pre-compiled .resources files from intermediate output.
                    // These are generated by CoreResGen from .resx files (which come from
                    // FSComp.txt, FSIstrings.txt, etc.). They only change when the .txt
                    // source files change, so reusing them from the intermediate directory is safe.
                    let resourceFlags =
                        if dtb.IntermediateOutputPath.Length > 0 then
                            System.IO.Directory.GetFiles(dtb.IntermediateOutputPath, "*.resources")
                            |> Array.map (fun r -> "--resource:" + r)
                        else [||]
                    let flagsOnly = Array.append flagsOnly resourceFlags
                    let opts = checker.GetProjectOptionsFromCommandLineArgs(key, flagsOnly)
                    let options = { opts with SourceFiles = orderedSources }
                    cache.[key] <- (fsprojMtime, options)
                    return Ok options
        }

    member _.Invalidate(?fsprojPath: string) =
        match fsprojPath with
        | Some p -> cache.TryRemove(normalize p) |> ignore
        | None -> cache.Clear()

    member internal _.CacheCount = cache.Count

    member internal _.HasCachedProject(fsprojPath: string) =
        cache.ContainsKey(normalize fsprojPath)

    member internal _.InjectTestEntry(fsprojPath: string, options: FSharpProjectOptions) =
        let key = normalize fsprojPath
        cache.[key] <- (System.DateTime.MinValue, options)
