module EmittedIL.RecordTypeSpreads

open FSharp.Test
open FSharp.Test.Compiler

/// Various types in the System.Diagnostics.CodeAnalysis namespace will be generated by the compiler
/// for the Framework target but will be included in the runtime for the .NET (Core) target.
/// Since the only IL that is material here is the field names, types, and ordering,
/// and since the spread logic is entirely framework/runtime-agnostic,
/// it is simpler to run these tests only for the .NET (Core) target.
type TheoryAttribute = TheoryForNETCOREAPPAttribute

let [<Literal>] SupportedLangVersion = "preview"

let verifyCompilation compilation =
    compilation
    |> withLangVersion SupportedLangVersion
    |> asExe
    |> withEmbeddedPdb
    |> withEmbedAllSource
    |> ignoreWarnings
    |> compile
    |> verifyILBaseline

[<Theory; FileInlineData("Type_ExplicitShadowsSpread.fs", Realsig = BooleanOptions.True, Optimize = BooleanOptions.True)>]
let Type_ExplicitShadowsSpread_fs compilation =
    compilation
    |> getCompilation
    |> verifyCompilation

[<Theory; FileInlineData("Type_NoOverlap_Explicit_Spread.fs", Realsig = BooleanOptions.True, Optimize = BooleanOptions.True)>]
let Type_NoOverlap_Explicit_Spread_fs compilation =
    compilation
    |> getCompilation
    |> verifyCompilation

[<Theory; FileInlineData("Type_NoOverlap_Spread_Explicit.fs", Realsig = BooleanOptions.True, Optimize = BooleanOptions.True)>]
let Type_NoOverlap_Spread_Explicit_fs compilation =
    compilation
    |> getCompilation
    |> verifyCompilation

[<Theory; FileInlineData("Type_NoOverlap_Spread_Spread.fs", Realsig = BooleanOptions.True, Optimize = BooleanOptions.True)>]
let Type_NoOverlap_Spread_Spread_fs compilation =
    compilation
    |> getCompilation
    |> verifyCompilation

[<Theory; FileInlineData("Type_NoOverlap_SpreadFromAnon.fs", Realsig = BooleanOptions.True, Optimize = BooleanOptions.True)>]
let Type_NoOverlap_SpreadFromAnon_fs compilation =
    compilation
    |> getCompilation
    |> verifyCompilation

[<Theory; FileInlineData("Type_SpreadShadowsSpread.fs", Realsig = BooleanOptions.True, Optimize = BooleanOptions.True)>]
let Type_SpreadShadowsSpread_fs compilation =
    compilation
    |> getCompilation
    |> verifyCompilation

[<Theory; FileInlineData("Type_SpreadShadowsExplicit.fs", Realsig = BooleanOptions.True, Optimize = BooleanOptions.True)>]
let Type_SpreadShadowsExplicit_fs compilation =
    compilation
    |> getCompilation
    |> verifyCompilation
