rem DIR=c:\dd\MQFSharp_1\binaries\x86ret\bin\i386\
set DIR=c:\dd\MQFSharp_1\binaries\x86chk\bin\i386\
set PPDIR="c:\Program Files\FSharpPowerPack-2.0.0.0\bin\"
copy %DIR%Fsc.exe
copy %DIR%Fsc.pdb
copy %DIR%Fsc.xml
copy %DIR%FSharp.Build.dll
copy %DIR%FSharp.Build.pdb
copy %DIR%FSharp.Build.xml
copy %DIR%FSharp.Compiler.Interactive.Settings.dll
copy %DIR%FSharp.Compiler.Interactive.Settings.pdb
copy %DIR%FSharp.Compiler.Interactive.Settings.xml
copy %DIR%FSharp.Compiler.dll
copy %DIR%FSharp.Compiler.pdb
copy %DIR%FSharp.Compiler.xml
copy %DIR%FSharp.Compiler.Server.Shared.dll
copy %DIR%FSharp.Compiler.Server.Shared.pdb
copy %DIR%FSharp.Compiler.Server.Shared.xml
copy %DIR%FSharp.Core.dll
copy %DIR%FSharp.Core.optdata
copy %DIR%FSharp.Core.sigdata
copy %DIR%FSharp.Core.pdb
copy %DIR%FSharp.Core.xml
copy %DIR%Fsi.exe
copy %DIR%Fsi.pdb
copy %DIR%Fsi.xml
copy %DIR%Microsoft.FSharp.targets
REM PowerPack from codeplex
copy %PPDIR%FSharp.PowerPack.Build.Tasks.dll
copy %PPDIR%FSharp.PowerPack.Build.Tasks.pdb
copy %PPDIR%FSharp.PowerPack.Build.Tasks.xml
copy %PPDIR%FSharp.PowerPack.targets
copy %PPDIR%FsLex.exe
copy %PPDIR%FsLex.pdb
copy %PPDIR%FsLex.xml
copy %PPDIR%FsYacc.exe
copy %PPDIR%FsYacc.pdb
copy %PPDIR%FsYacc.xml
