Lambda (i,
        IfThenElse (Call (None, op_Equality, [i, Value (1)]), Value ("one"),
                    IfThenElse (Call (None, op_Equality, [i, Value (2)]),
                                Value ("two"),
                                IfThenElse (Call (None, op_Equality,
                                                  [i, Value (3)]),
                                            Value ("three"),
                                            IfThenElse (Call (None, op_Equality,
                                                              [i, Value (4)]),
                                                        Value ("four"),
                                                        IfThenElse (Call (None,
                                                                          op_Equality,
                                                                          [i,
                                                                           Value (5)]),
                                                                    Value ("five"),
                                                                    IfThenElse (Call (None,
                                                                                      op_Equality,
                                                                                      [i,
                                                                                       Value (6)]),
                                                                                Value ("six"),
                                                                                IfThenElse (Call (None,
                                                                                                  op_Equality,
                                                                                                  [i,
                                                                                                   Value (7)]),
                                                                                            Value ("seven"),
                                                                                            IfThenElse (Call (None,
                                                                                                              op_Equality,
                                                                                                              [i,
                                                                                                               Value (8)]),
                                                                                                        Value ("eight"),
                                                                                                        IfThenElse (Call (None,
                                                                                                                          op_Equality,
                                                                                                                          [i,
                                                                                                                           Value (9)]),
                                                                                                                    Value ("nine"),
                                                                                                                    IfThenElse (Call (None,
                                                                                                                                      op_Equality,
                                                                                                                                      [i,
                                                                                                                                       Value (10)]),
                                                                                                                                Value ("ten"),
                                                                                                                                Value ("other"))))))))))))
