Lambda (d,
        IfThenElse (Call (None, op_Equality,
                          [d,
                           Call (None, MakeDecimal,
                                 [Value (1), Value (0), Value (0), Value (false),
                                  Value (0uy)])]), Value ("a"),
                    IfThenElse (Call (None, op_Equality,
                                      [d,
                                       Call (None, MakeDecimal,
                                             [Value (2), Value (0), Value (0),
                                              Value (false), Value (0uy)])]),
                                Value ("b"), Value ("other"))))
